apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: app
  labels:
    name: app
    type: netapi
spec:
  containers:
  - name: app-api
    image: netkubernetesangular:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 5000
    env:
      - name : ConnectionStrings__SQLServerConnection
        value: "Data Source=mssql-service,31433; Initial Catalog=InmuebleDB; User ID=sa; Password=NewStrongPassword1; TrustServerCertificate=True;"

