@NetKubernetesAngular_HostAddress = http://localhost:5000

POST {{NetKubernetesAngular_HostAddress}}/api/usuario/login
Content-Type: application/json
Accept: application/json

{
  "email": "DaveMore@gmail.com",
  "password": "Password123!"
}

###